version: '2.1'
services:
  db:
    image: mysql:5.7.22
    environment:
      - MYSQL_ROOT_PASSWORD=dehla_pakad_pass
      - MYSQL_DATABASE=dehla_pakad_db
      - MYSQL_USER=dehla_pakad_user
      - MYSQL_PASSWORD=dehla_pakad_pass
    platform: linux/x86_64
    volumes:
      - /home/ubuntu/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www
    command: /var/www/docker/api.sh
    env_file:
      - ./docker/bin/dev.env
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www
    command: /var/www/docker/worker.sh
    env_file:
      - ./docker/bin/dev.env
    depends_on:
      db:
        condition: service_healthy
