name: production deploy
on:
  push:
    branches:
      - master

jobs:
  build-test-deploy:
    name: Build, Test & Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check-out repo..
        uses: actions/checkout@v2
      
      - name: Install composer
        uses: php-actions/composer@v6

      - name: Using node.js ${{ matrix.node-version }}..
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing dependencies..
        run: npm install -g serverless
      
      - name: Injecting AWS creds..
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploying
        run: serverless deploy